### ISSUE TITLE
Where is the source?

### ISSUE THREAD

**Issue by az-rr** [SOELexicon/BurstAIOWallet#1]
As the title says.

**Comment by SOELexicon** [comment]
can you come to discord?

https://discord.io/BurstOfficial

**Comment by sontqq** [comment]
Would you answer and explain it publicly?

**Comment by SOELexicon** [comment]
if you take a look at my repos you'll see one thats the source, at the time of making this in april. focus at burstnation told me not to release the source despite me pressing for it to be open source. so when i left i released it all.

i hope thats a good enough answer for you lol

also the files aint obfuscated and anyone can use a decompiler to decompile and view the source for themselves anyway
